

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_28151 = Integer(28151); _sage_const_1 = Integer(1)
p = _sage_const_28151 
n = p - _sage_const_1 
ecm = ECM()
f = ecm.factor(n)
f = set(f)

for i in range(_sage_const_1 , n):
    primitive = True

    for j in f:
        g = pow(i, (p - _sage_const_1 ) // j, p)
        if g == _sage_const_1 :
            primitive = False
            break
    
    if primitive:
        print(i)
        break

